describe("path", function()
    describe("#append", function()
        it("creates a path from a list of path pieces", function()
            local path = require("grapple.path").append("a", "b", "c")
            assert.equals("a/b/c", path)
        end)
    end)

    describe("#make_relative", function()
        it("removes the common base path elements from the full path", function()
            local full_path = require("grapple.path").append("/a/b/c")
            local base_path = require("grapple.path").append("/a/b")
            local relative_path = require("grapple.path").make_relative(full_path, base_path)
            assert.equals("c", relative_path)
        end)

        it("does not remove uncommon path elements from the full path", function()
            local full_path = require("grapple.path").append("/a/b/c")
            local base_path = require("grapple.path").append("/c/d/e")
            local relative_path = require("grapple.path").make_relative(full_path, base_path)
            assert.equals("/a/b/c", relative_path)
        end)
    end)
end)
