local App = require("grapple.app")
local Util = require("grapple.util")

describe("App", function()
    describe(".update", function()
        it("defines the default scopes", function()
            local app = App:new()
            app:update()
            local names = vim.tbl_keys(app.scope_manager.scopes)
            table.sort(names, Util.as_lower)
            assert.same({ "cwd", "git", "git_branch", "global", "lsp", "static" }, names)
        end)
    end)
end)
