local ScopeManager = require("grapple.scope_manager")
local Util = require("grapple.util")

describe("TagContent", function()
    describe(".list", function()
        it("returns a list of scopes, sorted by name", function()
            local sm = ScopeManager:new()
            sm:define({ name = "c", resolver = function() end })
            sm:define({ name = "b", resolver = function() end })
            sm:define({ name = "a", resolver = function() end })
            assert.is_same({ "a", "b", "c" }, vim.tbl_map(Util.pick("name"), sm:list()))
        end)
    end)
end)
